// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/embeddings/gemma.dart';
import 'api/embeddings/jina_v3.dart';
import 'api/embeddings/qwen3.dart';
import 'api/ort.dart';
import 'api/tokenizer.dart';
import 'api/utils.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 272288121;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flutter_embedder',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  GemmaEmbedder crateApiEmbeddingsGemmaGemmaEmbedderCreate({
    required String modelPath,
    required String tokenizerPath,
  });

  List<Float32List> crateApiEmbeddingsGemmaGemmaEmbedderEmbed({
    required GemmaEmbedder that,
    required List<String> texts,
  });

  String crateApiEmbeddingsGemmaGemmaEmbedderFormatDocument({
    required String text,
  });

  String crateApiEmbeddingsGemmaGemmaEmbedderFormatQuery({
    required String query,
  });

  JinaV3Embedder crateApiEmbeddingsJinaV3JinaV3EmbedderCreate({
    required String modelPath,
    required String tokenizerPath,
  });

  List<Float32List> crateApiEmbeddingsJinaV3JinaV3EmbedderEmbed({
    required JinaV3Embedder that,
    required List<String> texts,
    required PlatformInt64 taskId,
  });

  String crateApiEmbeddingsJinaV3JinaV3EmbedderFormatDocument({
    required String text,
  });

  String crateApiEmbeddingsJinaV3JinaV3EmbedderFormatQuery({
    required String query,
  });

  Qwen3Embedder crateApiEmbeddingsQwen3Qwen3EmbedderCreate({
    required String modelPath,
    required String tokenizerPath,
  });

  List<Float32List> crateApiEmbeddingsQwen3Qwen3EmbedderEmbed({
    required Qwen3Embedder that,
    required List<String> texts,
  });

  String crateApiEmbeddingsQwen3Qwen3EmbedderFormatDocument({
    required String text,
  });

  String crateApiEmbeddingsQwen3Qwen3EmbedderFormatQuery({
    required String query,
  });

  int crateApiTokenizerAddSpecialTokens({
    required BigInt tokenizerId,
    required List<String> tokens,
  });

  double crateApiUtilsCosineDistance({
    required List<double> a,
    required List<double> b,
  });

  String crateApiTokenizerDecode({
    required BigInt tokenizerId,
    required List<int> ids,
    bool? skipSpecialTokens,
  });

  List<String> crateApiTokenizerDecodeBatch({
    required BigInt tokenizerId,
    required List<Uint32List> batchIds,
    bool? skipSpecialTokens,
  });

  Future<List<String>> crateApiTokenizerDecodeBatchAsync({
    required BigInt tokenizerId,
    required List<Uint32List> batchIds,
    bool? skipSpecialTokens,
  });

  EncodeOutput crateApiTokenizerEncode({
    required BigInt tokenizerId,
    required String text,
    bool? addSpecialTokens,
  });

  List<EncodeOutput> crateApiTokenizerEncodeBatch({
    required BigInt tokenizerId,
    required List<String> texts,
    bool? addSpecialTokens,
  });

  Future<List<EncodeOutput>> crateApiTokenizerEncodeBatchAsync({
    required BigInt tokenizerId,
    required List<String> texts,
    bool? addSpecialTokens,
  });

  Future<void> crateApiInitApp();

  bool crateApiOrtInitOrt({required String name, String? path});

  BigInt crateApiTokenizerLoadTokenizerFromBytes({required List<int> bytes});

  BigInt crateApiTokenizerLoadTokenizerFromBytesWithSpecialTokens({
    required List<int> bytes,
    required List<String> specialTokens,
  });

  BigInt crateApiTokenizerLoadTokenizerFromFile({required String path});

  BigInt crateApiTokenizerLoadTokenizerFromFileWithSpecialTokens({
    required String path,
    required List<String> specialTokens,
  });

  BigInt crateApiTokenizerLoadTokenizerFromJson({required String json});

  BigInt crateApiTokenizerLoadTokenizerFromJsonWithSpecialTokens({
    required String json,
    required List<String> specialTokens,
  });

  Float32List crateApiUtilsMeanPooling({
    required Array2F32 embeddings,
    required List<int> attentionMask,
  });

  Future<Float32List> crateApiUtilsMeanPoolingNdarray({
    required Array2F32 embeddings,
    required List<int> attentionMask,
  });

  Float32List crateApiUtilsMeanPoolingVec({
    required List<Float32List> embeddings,
    required List<int> attentionMask,
  });

  Float32List crateApiUtilsNormalize({required List<double> embedding});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Array2F32;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Array2F32;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Array2F32Ptr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GemmaEmbedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GemmaEmbedder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GemmaEmbedderPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JinaV3Embedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JinaV3Embedder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_JinaV3EmbedderPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Qwen3Embedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Qwen3Embedder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_Qwen3EmbedderPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  GemmaEmbedder crateApiEmbeddingsGemmaGemmaEmbedderCreate({
    required String modelPath,
    required String tokenizerPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(tokenizerPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbeddingsGemmaGemmaEmbedderCreateConstMeta,
        argValues: [modelPath, tokenizerPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsGemmaGemmaEmbedderCreateConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_create",
        argNames: ["modelPath", "tokenizerPath"],
      );

  @override
  List<Float32List> crateApiEmbeddingsGemmaGemmaEmbedderEmbed({
    required GemmaEmbedder that,
    required List<String> texts,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
            that,
            serializer,
          );
          sse_encode_list_String(texts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbeddingsGemmaGemmaEmbedderEmbedConstMeta,
        argValues: [that, texts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsGemmaGemmaEmbedderEmbedConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_embed",
        argNames: ["that", "texts"],
      );

  @override
  String crateApiEmbeddingsGemmaGemmaEmbedderFormatDocument({
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbeddingsGemmaGemmaEmbedderFormatDocumentConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiEmbeddingsGemmaGemmaEmbedderFormatDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_format_document",
        argNames: ["text"],
      );

  @override
  String crateApiEmbeddingsGemmaGemmaEmbedderFormatQuery({
    required String query,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbeddingsGemmaGemmaEmbedderFormatQueryConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsGemmaGemmaEmbedderFormatQueryConstMeta =>
      const TaskConstMeta(
        debugName: "GemmaEmbedder_format_query",
        argNames: ["query"],
      );

  @override
  JinaV3Embedder crateApiEmbeddingsJinaV3JinaV3EmbedderCreate({
    required String modelPath,
    required String tokenizerPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(tokenizerPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbeddingsJinaV3JinaV3EmbedderCreateConstMeta,
        argValues: [modelPath, tokenizerPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsJinaV3JinaV3EmbedderCreateConstMeta =>
      const TaskConstMeta(
        debugName: "JinaV3Embedder_create",
        argNames: ["modelPath", "tokenizerPath"],
      );

  @override
  List<Float32List> crateApiEmbeddingsJinaV3JinaV3EmbedderEmbed({
    required JinaV3Embedder that,
    required List<String> texts,
    required PlatformInt64 taskId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
            that,
            serializer,
          );
          sse_encode_list_String(texts, serializer);
          sse_encode_i_64(taskId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbeddingsJinaV3JinaV3EmbedderEmbedConstMeta,
        argValues: [that, texts, taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsJinaV3JinaV3EmbedderEmbedConstMeta =>
      const TaskConstMeta(
        debugName: "JinaV3Embedder_embed",
        argNames: ["that", "texts", "taskId"],
      );

  @override
  String crateApiEmbeddingsJinaV3JinaV3EmbedderFormatDocument({
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiEmbeddingsJinaV3JinaV3EmbedderFormatDocumentConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiEmbeddingsJinaV3JinaV3EmbedderFormatDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "JinaV3Embedder_format_document",
        argNames: ["text"],
      );

  @override
  String crateApiEmbeddingsJinaV3JinaV3EmbedderFormatQuery({
    required String query,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbeddingsJinaV3JinaV3EmbedderFormatQueryConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiEmbeddingsJinaV3JinaV3EmbedderFormatQueryConstMeta =>
      const TaskConstMeta(
        debugName: "JinaV3Embedder_format_query",
        argNames: ["query"],
      );

  @override
  Qwen3Embedder crateApiEmbeddingsQwen3Qwen3EmbedderCreate({
    required String modelPath,
    required String tokenizerPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(tokenizerPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbeddingsQwen3Qwen3EmbedderCreateConstMeta,
        argValues: [modelPath, tokenizerPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsQwen3Qwen3EmbedderCreateConstMeta =>
      const TaskConstMeta(
        debugName: "Qwen3Embedder_create",
        argNames: ["modelPath", "tokenizerPath"],
      );

  @override
  List<Float32List> crateApiEmbeddingsQwen3Qwen3EmbedderEmbed({
    required Qwen3Embedder that,
    required List<String> texts,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
            that,
            serializer,
          );
          sse_encode_list_String(texts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbeddingsQwen3Qwen3EmbedderEmbedConstMeta,
        argValues: [that, texts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsQwen3Qwen3EmbedderEmbedConstMeta =>
      const TaskConstMeta(
        debugName: "Qwen3Embedder_embed",
        argNames: ["that", "texts"],
      );

  @override
  String crateApiEmbeddingsQwen3Qwen3EmbedderFormatDocument({
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbeddingsQwen3Qwen3EmbedderFormatDocumentConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiEmbeddingsQwen3Qwen3EmbedderFormatDocumentConstMeta =>
      const TaskConstMeta(
        debugName: "Qwen3Embedder_format_document",
        argNames: ["text"],
      );

  @override
  String crateApiEmbeddingsQwen3Qwen3EmbedderFormatQuery({
    required String query,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbeddingsQwen3Qwen3EmbedderFormatQueryConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbeddingsQwen3Qwen3EmbedderFormatQueryConstMeta =>
      const TaskConstMeta(
        debugName: "Qwen3Embedder_format_query",
        argNames: ["query"],
      );

  @override
  int crateApiTokenizerAddSpecialTokens({
    required BigInt tokenizerId,
    required List<String> tokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tokenizerId, serializer);
          sse_encode_list_String(tokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerAddSpecialTokensConstMeta,
        argValues: [tokenizerId, tokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerAddSpecialTokensConstMeta =>
      const TaskConstMeta(
        debugName: "add_special_tokens",
        argNames: ["tokenizerId", "tokens"],
      );

  @override
  double crateApiUtilsCosineDistance({
    required List<double> a,
    required List<double> b,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(a, serializer);
          sse_encode_list_prim_f_32_loose(b, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUtilsCosineDistanceConstMeta,
        argValues: [a, b],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsCosineDistanceConstMeta =>
      const TaskConstMeta(debugName: "cosine_distance", argNames: ["a", "b"]);

  @override
  String crateApiTokenizerDecode({
    required BigInt tokenizerId,
    required List<int> ids,
    bool? skipSpecialTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tokenizerId, serializer);
          sse_encode_list_prim_u_32_loose(ids, serializer);
          sse_encode_opt_box_autoadd_bool(skipSpecialTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerDecodeConstMeta,
        argValues: [tokenizerId, ids, skipSpecialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerDecodeConstMeta => const TaskConstMeta(
    debugName: "decode",
    argNames: ["tokenizerId", "ids", "skipSpecialTokens"],
  );

  @override
  List<String> crateApiTokenizerDecodeBatch({
    required BigInt tokenizerId,
    required List<Uint32List> batchIds,
    bool? skipSpecialTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tokenizerId, serializer);
          sse_encode_list_list_prim_u_32_strict(batchIds, serializer);
          sse_encode_opt_box_autoadd_bool(skipSpecialTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerDecodeBatchConstMeta,
        argValues: [tokenizerId, batchIds, skipSpecialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerDecodeBatchConstMeta =>
      const TaskConstMeta(
        debugName: "decode_batch",
        argNames: ["tokenizerId", "batchIds", "skipSpecialTokens"],
      );

  @override
  Future<List<String>> crateApiTokenizerDecodeBatchAsync({
    required BigInt tokenizerId,
    required List<Uint32List> batchIds,
    bool? skipSpecialTokens,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tokenizerId, serializer);
          sse_encode_list_list_prim_u_32_strict(batchIds, serializer);
          sse_encode_opt_box_autoadd_bool(skipSpecialTokens, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerDecodeBatchAsyncConstMeta,
        argValues: [tokenizerId, batchIds, skipSpecialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerDecodeBatchAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "decode_batch_async",
        argNames: ["tokenizerId", "batchIds", "skipSpecialTokens"],
      );

  @override
  EncodeOutput crateApiTokenizerEncode({
    required BigInt tokenizerId,
    required String text,
    bool? addSpecialTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tokenizerId, serializer);
          sse_encode_String(text, serializer);
          sse_encode_opt_box_autoadd_bool(addSpecialTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encode_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerEncodeConstMeta,
        argValues: [tokenizerId, text, addSpecialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerEncodeConstMeta => const TaskConstMeta(
    debugName: "encode",
    argNames: ["tokenizerId", "text", "addSpecialTokens"],
  );

  @override
  List<EncodeOutput> crateApiTokenizerEncodeBatch({
    required BigInt tokenizerId,
    required List<String> texts,
    bool? addSpecialTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tokenizerId, serializer);
          sse_encode_list_String(texts, serializer);
          sse_encode_opt_box_autoadd_bool(addSpecialTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_encode_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerEncodeBatchConstMeta,
        argValues: [tokenizerId, texts, addSpecialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerEncodeBatchConstMeta =>
      const TaskConstMeta(
        debugName: "encode_batch",
        argNames: ["tokenizerId", "texts", "addSpecialTokens"],
      );

  @override
  Future<List<EncodeOutput>> crateApiTokenizerEncodeBatchAsync({
    required BigInt tokenizerId,
    required List<String> texts,
    bool? addSpecialTokens,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(tokenizerId, serializer);
          sse_encode_list_String(texts, serializer);
          sse_encode_opt_box_autoadd_bool(addSpecialTokens, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_encode_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerEncodeBatchAsyncConstMeta,
        argValues: [tokenizerId, texts, addSpecialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerEncodeBatchAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "encode_batch_async",
        argNames: ["tokenizerId", "texts", "addSpecialTokens"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiOrtInitOrt({required String name, String? path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiOrtInitOrtConstMeta,
        argValues: [name, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOrtInitOrtConstMeta =>
      const TaskConstMeta(debugName: "init_ort", argNames: ["name", "path"]);

  @override
  BigInt crateApiTokenizerLoadTokenizerFromBytes({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerLoadTokenizerFromBytesConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerLoadTokenizerFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "load_tokenizer_from_bytes",
        argNames: ["bytes"],
      );

  @override
  BigInt crateApiTokenizerLoadTokenizerFromBytesWithSpecialTokens({
    required List<int> bytes,
    required List<String> specialTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_list_String(specialTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiTokenizerLoadTokenizerFromBytesWithSpecialTokensConstMeta,
        argValues: [bytes, specialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTokenizerLoadTokenizerFromBytesWithSpecialTokensConstMeta =>
      const TaskConstMeta(
        debugName: "load_tokenizer_from_bytes_with_special_tokens",
        argNames: ["bytes", "specialTokens"],
      );

  @override
  BigInt crateApiTokenizerLoadTokenizerFromFile({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerLoadTokenizerFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerLoadTokenizerFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "load_tokenizer_from_file",
        argNames: ["path"],
      );

  @override
  BigInt crateApiTokenizerLoadTokenizerFromFileWithSpecialTokens({
    required String path,
    required List<String> specialTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_String(specialTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiTokenizerLoadTokenizerFromFileWithSpecialTokensConstMeta,
        argValues: [path, specialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTokenizerLoadTokenizerFromFileWithSpecialTokensConstMeta =>
      const TaskConstMeta(
        debugName: "load_tokenizer_from_file_with_special_tokens",
        argNames: ["path", "specialTokens"],
      );

  @override
  BigInt crateApiTokenizerLoadTokenizerFromJson({required String json}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTokenizerLoadTokenizerFromJsonConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTokenizerLoadTokenizerFromJsonConstMeta =>
      const TaskConstMeta(
        debugName: "load_tokenizer_from_json",
        argNames: ["json"],
      );

  @override
  BigInt crateApiTokenizerLoadTokenizerFromJsonWithSpecialTokens({
    required String json,
    required List<String> specialTokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          sse_encode_list_String(specialTokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiTokenizerLoadTokenizerFromJsonWithSpecialTokensConstMeta,
        argValues: [json, specialTokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiTokenizerLoadTokenizerFromJsonWithSpecialTokensConstMeta =>
      const TaskConstMeta(
        debugName: "load_tokenizer_from_json_with_special_tokens",
        argNames: ["json", "specialTokens"],
      );

  @override
  Float32List crateApiUtilsMeanPooling({
    required Array2F32 embeddings,
    required List<int> attentionMask,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
            embeddings,
            serializer,
          );
          sse_encode_list_prim_u_32_loose(attentionMask, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilsMeanPoolingConstMeta,
        argValues: [embeddings, attentionMask],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsMeanPoolingConstMeta => const TaskConstMeta(
    debugName: "mean_pooling",
    argNames: ["embeddings", "attentionMask"],
  );

  @override
  Future<Float32List> crateApiUtilsMeanPoolingNdarray({
    required Array2F32 embeddings,
    required List<int> attentionMask,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
            embeddings,
            serializer,
          );
          sse_encode_list_prim_u_32_loose(attentionMask, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilsMeanPoolingNdarrayConstMeta,
        argValues: [embeddings, attentionMask],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsMeanPoolingNdarrayConstMeta =>
      const TaskConstMeta(
        debugName: "mean_pooling_ndarray",
        argNames: ["embeddings", "attentionMask"],
      );

  @override
  Float32List crateApiUtilsMeanPoolingVec({
    required List<Float32List> embeddings,
    required List<int> attentionMask,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_f_32_strict(embeddings, serializer);
          sse_encode_list_prim_u_32_loose(attentionMask, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilsMeanPoolingVecConstMeta,
        argValues: [embeddings, attentionMask],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsMeanPoolingVecConstMeta =>
      const TaskConstMeta(
        debugName: "mean_pooling_vec",
        argNames: ["embeddings", "attentionMask"],
      );

  @override
  Float32List crateApiUtilsNormalize({required List<double> embedding}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(embedding, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUtilsNormalizeConstMeta,
        argValues: [embedding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUtilsNormalizeConstMeta =>
      const TaskConstMeta(debugName: "normalize", argNames: ["embedding"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Array2F32 => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Array2F32 => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GemmaEmbedder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GemmaEmbedder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JinaV3Embedder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JinaV3Embedder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Qwen3Embedder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Qwen3Embedder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  GemmaEmbedder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JinaV3Embedder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JinaV3EmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Qwen3Embedder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Qwen3EmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GemmaEmbedder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JinaV3Embedder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JinaV3EmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Qwen3Embedder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Qwen3EmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Array2F32
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Array2F32Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Array2F32
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Array2F32Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GemmaEmbedder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JinaV3Embedder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JinaV3EmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Qwen3Embedder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Qwen3EmbedderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EncodeOutput dco_decode_encode_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EncodeOutput(
      ids: dco_decode_list_prim_u_32_strict(arr[0]),
      attentionMask: dco_decode_list_prim_u_32_strict(arr[1]),
      typeIds: dco_decode_list_prim_u_32_strict(arr[2]),
      specialTokensMask: dco_decode_list_prim_u_32_strict(arr[3]),
      offsets: dco_decode_list_token_offsets(arr[4]),
      tokens: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<EncodeOutput> dco_decode_list_encode_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_encode_output).toList();
  }

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_f_32_strict)
        .toList();
  }

  @protected
  List<Uint32List> dco_decode_list_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_u_32_strict)
        .toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TokenOffsets> dco_decode_list_token_offsets(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_token_offsets).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  TokenOffsets dco_decode_token_offsets(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TokenOffsets(
      start: dco_decode_u_32(arr[0]),
      end: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  GemmaEmbedder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JinaV3Embedder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JinaV3EmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Qwen3Embedder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Qwen3EmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GemmaEmbedder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JinaV3Embedder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JinaV3EmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Qwen3Embedder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Qwen3EmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Array2F32
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Array2F32Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Array2F32
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Array2F32Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GemmaEmbedder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GemmaEmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JinaV3Embedder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JinaV3EmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Qwen3Embedder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return Qwen3EmbedderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  EncodeOutput sse_decode_encode_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ids = sse_decode_list_prim_u_32_strict(deserializer);
    var var_attentionMask = sse_decode_list_prim_u_32_strict(deserializer);
    var var_typeIds = sse_decode_list_prim_u_32_strict(deserializer);
    var var_specialTokensMask = sse_decode_list_prim_u_32_strict(deserializer);
    var var_offsets = sse_decode_list_token_offsets(deserializer);
    var var_tokens = sse_decode_list_String(deserializer);
    return EncodeOutput(
      ids: var_ids,
      attentionMask: var_attentionMask,
      typeIds: var_typeIds,
      specialTokensMask: var_specialTokensMask,
      offsets: var_offsets,
      tokens: var_tokens,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<EncodeOutput> sse_decode_list_encode_output(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EncodeOutput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_encode_output(deserializer));
    }
    return ans_;
  }

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Float32List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_f_32_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint32List> sse_decode_list_list_prim_u_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint32List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_32_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TokenOffsets> sse_decode_list_token_offsets(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TokenOffsets>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_token_offsets(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TokenOffsets sse_decode_token_offsets(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_u_32(deserializer);
    var var_end = sse_decode_u_32(deserializer);
    return TokenOffsets(start: var_start, end: var_end);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    GemmaEmbedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GemmaEmbedderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    JinaV3Embedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JinaV3EmbedderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    Qwen3Embedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Qwen3EmbedderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    GemmaEmbedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GemmaEmbedderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    JinaV3Embedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JinaV3EmbedderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    Qwen3Embedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Qwen3EmbedderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
    Array2F32 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Array2F32Impl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArray2f32(
    Array2F32 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Array2F32Impl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGemmaEmbedder(
    GemmaEmbedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GemmaEmbedderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJinaV3Embedder(
    JinaV3Embedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JinaV3EmbedderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwen3Embedder(
    Qwen3Embedder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as Qwen3EmbedderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_encode_output(EncodeOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_32_strict(self.ids, serializer);
    sse_encode_list_prim_u_32_strict(self.attentionMask, serializer);
    sse_encode_list_prim_u_32_strict(self.typeIds, serializer);
    sse_encode_list_prim_u_32_strict(self.specialTokensMask, serializer);
    sse_encode_list_token_offsets(self.offsets, serializer);
    sse_encode_list_String(self.tokens, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_encode_output(
    List<EncodeOutput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_encode_output(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_f_32_strict(
    List<Float32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_f_32_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_32_strict(
    List<Uint32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_32_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(
      self is Uint32List ? self : Uint32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_token_offsets(
    List<TokenOffsets> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_token_offsets(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_token_offsets(TokenOffsets self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.start, serializer);
    sse_encode_u_32(self.end, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class Array2F32Impl extends RustOpaque implements Array2F32 {
  // Not to be used by end users
  Array2F32Impl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Array2F32Impl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Array2F32,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Array2F32,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Array2F32Ptr,
  );
}

@sealed
class GemmaEmbedderImpl extends RustOpaque implements GemmaEmbedder {
  // Not to be used by end users
  GemmaEmbedderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GemmaEmbedderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_GemmaEmbedder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_GemmaEmbedder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_GemmaEmbedderPtr,
  );

  List<Float32List> embed({required List<String> texts}) => RustLib.instance.api
      .crateApiEmbeddingsGemmaGemmaEmbedderEmbed(that: this, texts: texts);
}

@sealed
class JinaV3EmbedderImpl extends RustOpaque implements JinaV3Embedder {
  // Not to be used by end users
  JinaV3EmbedderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  JinaV3EmbedderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_JinaV3Embedder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_JinaV3Embedder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_JinaV3EmbedderPtr,
  );

  List<Float32List> embed({
    required List<String> texts,
    required PlatformInt64 taskId,
  }) => RustLib.instance.api.crateApiEmbeddingsJinaV3JinaV3EmbedderEmbed(
    that: this,
    texts: texts,
    taskId: taskId,
  );
}

@sealed
class Qwen3EmbedderImpl extends RustOpaque implements Qwen3Embedder {
  // Not to be used by end users
  Qwen3EmbedderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  Qwen3EmbedderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Qwen3Embedder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Qwen3Embedder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_Qwen3EmbedderPtr,
  );

  List<Float32List> embed({required List<String> texts}) => RustLib.instance.api
      .crateApiEmbeddingsQwen3Qwen3EmbedderEmbed(that: this, texts: texts);
}
