// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../ort.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pick_embedding_tensor`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BgeEmbedder>>
abstract class BgeEmbedder implements RustOpaqueInterface {
  static BgeEmbedder create({
    required String modelPath,
    required String tokenizerPath,
  }) => RustLib.instance.api.crateApiEmbeddingsBgeBgeEmbedderCreate(
    modelPath: modelPath,
    tokenizerPath: tokenizerPath,
  );

  static BgeEmbedder createWithOptions({
    required String modelPath,
    required String tokenizerPath,
    OrtInitOptions? ortOptions,
  }) => RustLib.instance.api.crateApiEmbeddingsBgeBgeEmbedderCreateWithOptions(
    modelPath: modelPath,
    tokenizerPath: tokenizerPath,
    ortOptions: ortOptions,
  );

  List<Float32List> embed({required List<String> texts});

  static String formatDocument({required String text}) => RustLib.instance.api
      .crateApiEmbeddingsBgeBgeEmbedderFormatDocument(text: text);

  static String formatQuery({required String query}) => RustLib.instance.api
      .crateApiEmbeddingsBgeBgeEmbedderFormatQuery(query: query);
}
