// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GemmaEmbedder>>
abstract class GemmaEmbedder implements RustOpaqueInterface {
  static GemmaEmbedder create({
    required String modelPath,
    required String tokenizerPath,
  }) => RustLib.instance.api.crateApiEmbeddingsGemmaGemmaEmbedderCreate(
    modelPath: modelPath,
    tokenizerPath: tokenizerPath,
  );

  List<Float32List> embed({required List<String> texts});

  static String formatDocument({required String text}) => RustLib.instance.api
      .crateApiEmbeddingsGemmaGemmaEmbedderFormatDocument(text: text);

  static String formatQuery({required String query}) => RustLib.instance.api
      .crateApiEmbeddingsGemmaGemmaEmbedderFormatQuery(query: query);
}
