// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fit_mask`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JinaV3Embedder>>
abstract class JinaV3Embedder implements RustOpaqueInterface {
  static JinaV3Embedder create({
    required String modelPath,
    required String tokenizerPath,
  }) => RustLib.instance.api.crateApiEmbeddingsJinaV3JinaV3EmbedderCreate(
    modelPath: modelPath,
    tokenizerPath: tokenizerPath,
  );

  List<Float32List> embed({
    required List<String> texts,
    required PlatformInt64 taskId,
  });

  static String formatDocument({required String text}) => RustLib.instance.api
      .crateApiEmbeddingsJinaV3JinaV3EmbedderFormatDocument(text: text);

  static String formatQuery({required String query}) => RustLib.instance.api
      .crateApiEmbeddingsJinaV3JinaV3EmbedderFormatQuery(query: query);
}
