// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `take`

double cosineDistance({required List<double> a, required List<double> b}) =>
    RustLib.instance.api.crateApiUtilsCosineDistance(a: a, b: b);

Future<Float32List> meanPoolingNdarray({
  required Array2F32 embeddings,
  required List<int> attentionMask,
}) => RustLib.instance.api.crateApiUtilsMeanPoolingNdarray(
  embeddings: embeddings,
  attentionMask: attentionMask,
);

Float32List meanPooling({
  required Array2F32 embeddings,
  required List<int> attentionMask,
}) => RustLib.instance.api.crateApiUtilsMeanPooling(
  embeddings: embeddings,
  attentionMask: attentionMask,
);

Float32List meanPoolingVec({
  required List<Float32List> embeddings,
  required List<int> attentionMask,
}) => RustLib.instance.api.crateApiUtilsMeanPoolingVec(
  embeddings: embeddings,
  attentionMask: attentionMask,
);

Float32List normalize({required List<double> embedding}) =>
    RustLib.instance.api.crateApiUtilsNormalize(embedding: embedding);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Array2 < f32 >>>
abstract class Array2F32 implements RustOpaqueInterface {}
